In [1]:
import pandas as pd
import numpy as np

In [2]:
attendance = pd.DataFrame({
    'emp_id': ['E1', 'E2', 'E3', 'E4', 'E5', 'E6'],
    'department': ['HR', 'IT', None, 'Finance', 'IT', None],
    'days_present': [20, None, 22, 18, None, 19],
    'performance_score': [85, 90, None, None, 88, 92]
})

### Tasks:

(a) Identify the number of missing values in each column (2 marks)

(b) Drop rows where department is missing. Print the resulting DataFrame (2 marks)

(c) Fill missing values in days_present using the column mean (2 marks)

(d) Fill missing values in performance_score using forward fill (2 marks)

(e) After all cleaning steps, verify that no missing values remain (2 marks)

In [3]:
attendance.head()

  emp_id department  days_present  performance_score
0     E1         HR          20.0               85.0
1     E2         IT           NaN               90.0
2     E3        NaN          22.0                NaN
3     E4    Finance          18.0                NaN
4     E5         IT           NaN               88.0

In [4]:
attendance.isna().sum()

emp_id               0
department           2
days_present         2
performance_score    2
dtype: int64

In [5]:
attendance.isnull().sum()

emp_id               0
department           2
days_present         2
performance_score    2
dtype: int64

In [6]:
print(f"Shape Before Dropping records with missing department: {attendance.shape}")
attendance.dropna(subset=['department'], inplace=True)
print(f"Shape After Dropping records with missing department: {attendance.shape}")

Shape Before Dropping records with missing department: (6, 4)
Shape After Dropping records with missing department: (4, 4)

In [7]:
attendance

  emp_id department  days_present  performance_score
0     E1         HR          20.0               85.0
1     E2         IT           NaN               90.0
3     E4    Finance          18.0                NaN
4     E5         IT           NaN               88.0

In [10]:
days_present_mean = attendance['days_present'].mean()
attendance.fillna({'days_present': days_present_mean}, inplace=True)

  emp_id department  days_present  performance_score
0     E1         HR          20.0               85.0
1     E2         IT          19.0               90.0
3     E4    Finance          18.0                NaN
4     E5         IT          19.0               88.0

In [13]:
attendance['performance_score'] = attendance['performance_score'].ffill()

In [14]:
attendance

  emp_id department  days_present  performance_score
0     E1         HR          20.0               85.0
1     E2         IT          19.0               90.0
3     E4    Finance          18.0               90.0
4     E5         IT          19.0               88.0

In [15]:
attendance.isna().sum()

emp_id               0
department           0
days_present         0
performance_score    0
dtype: int64