In [82]:
import pandas as pd
import numpy as np

from Assignment8 import total_revenue

Lookup Dictionary: {'P001': 'Laptop', 'P002': 'Mouse', 'P003': 'Desk', 'P004': 'Chair', 'P005': 'Monitor'}
Products with price > 100: ['Laptop', 'Desk', 'Chair', 'Monitor']
Product total revenue: {'P001': 6000, 'P002': 1250, 'P003': 3500, 'P004': 3000, 'P005': 3200}
Total Revenue: [6000 1250 3500 3000 3200]
Index of highest revenue: 0
Average revenue: 3390.0
Products having revenue more than average: ['P001' 'P003']
  product_id product_name     category  price  quantity  revenue
0       P001       Laptop  Electronics   1200         5     6000
1       P002        Mouse  Electronics     25        50     1250
2       P003         Desk    Furniture    350        10     3500
3       P004        Chair    Furniture    150        20     3000
4       P005      Monitor  Electronics    400         8     3200

In [83]:
orders = pd.DataFrame({
    'order_id': ['R01', 'R02', 'R03', 'R04', 'R05', 'R06', 'R07', 'R08', 'R01'],
    'customer_id': ['K1', 'K2', 'K3', 'K1', 'K4', 'K2', 'K5', 'K3', 'K1'],
    'product_id': ['W01', 'W02', 'W03', 'W04', 'W05', 'W01', 'W02', 'W03', 'W01'],
    'quantity': [2, 1, 3, 1, 2, 4, 1, 2, 2]
})

customers = pd.DataFrame({
    'customer_id': ['K1', 'K2', 'K3', 'K4', 'K5'],
    'name': ['  ravi KUMAR ', 'SITA sharma', 'amit PATEL', 'Neha Gupta', 'POOJA singh'],
    'region': ['north', 'SOUTH', ' West', 'North', 'south']
})

products = pd.DataFrame({
    'product_id': ['W01', 'W02', 'W03', 'W04', 'W05'],
    'product_name': ['Widget A', 'Widget B', 'Widget C', 'Widget D', 'Widget E'],
    'category': ['Electronics', 'Clothing', None, 'Electronics', 'Clothing'],
    'price': ['Rs. 500', 'Rs. 300', 'Rs. 800', 'Rs. 1200', 'Rs. 450']
})

In [84]:
print(orders.shape)
print(customers.shape)
print(products.shape)

(9, 4)
(5, 3)
(5, 4)

In [85]:
orders

  order_id customer_id product_id  quantity
0      R01          K1        W01         2
1      R02          K2        W02         1
2      R03          K3        W03         3
3      R04          K1        W04         1
4      R05          K4        W05         2
5      R06          K2        W01         4
6      R07          K5        W02         1
7      R08          K3        W03         2
8      R01          K1        W01         2

In [86]:
orders.describe(include='all')

       order_id customer_id product_id  quantity
count         9           9          9       9.0
unique        8           5          5       NaN
top         R01          K1        W01       NaN
freq          2           3          3       NaN
mean        NaN         NaN        NaN       2.0
std         NaN         NaN        NaN       1.0
min         NaN         NaN        NaN       1.0
25%         NaN         NaN        NaN       1.0
50%         NaN         NaN        NaN       2.0
75%         NaN         NaN        NaN       2.0
max         NaN         NaN        NaN       4.0

In [87]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     9 non-null      str
 1   customer_id  9 non-null      str
 2   product_id   9 non-null      str
 3   quantity     9 non-null      int64
dtypes: int64(1), str(3)
memory usage: 420.0 bytes

In [88]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    5 non-null      str
 1   product_name  5 non-null      str
 2   category      4 non-null      str
 3   price         5 non-null      str
dtypes: str(4)
memory usage: 292.0 bytes

In [89]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5 non-null      str
 1   name         5 non-null      str
 2   region       5 non-null      str
dtypes: str(3)
memory usage: 252.0 bytes

In [90]:
products

  product_id product_name     category     price
0        W01     Widget A  Electronics   Rs. 500
1        W02     Widget B     Clothing   Rs. 300
2        W03     Widget C          NaN   Rs. 800
3        W04     Widget D  Electronics  Rs. 1200
4        W05     Widget E     Clothing   Rs. 450

In [91]:
customers

  customer_id           name region
0          K1    ravi KUMAR   north
1          K2    SITA sharma  SOUTH
2          K3     amit PATEL   West
3          K4     Neha Gupta  North
4          K5    POOJA singh  south

In [92]:
## (a) Clean the orders DataFrame: remove duplicate rows (based on all columns) and reset the index. Print the shape before and after cleaning.
print(f"Before Removing Duplicates: {orders.shape}")
orders = orders.drop_duplicates(subset=orders.columns)
orders.reset_index()
print(f"After Removing Duplicates: {orders.shape}")

Before Removing Duplicates: (9, 4)
After Removing Duplicates: (8, 4)

In [93]:
orders

  order_id customer_id product_id  quantity
0      R01          K1        W01         2
1      R02          K2        W02         1
2      R03          K3        W03         3
3      R04          K1        W04         1
4      R05          K4        W05         2
5      R06          K2        W01         4
6      R07          K5        W02         1
7      R08          K3        W03         2

In [94]:
orders.duplicated(subset=orders.columns)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [95]:
customers

  customer_id           name region
0          K1    ravi KUMAR   north
1          K2    SITA sharma  SOUTH
2          K3     amit PATEL   West
3          K4     Neha Gupta  North
4          K5    POOJA singh  south

In [96]:
## Clean the customers DataFrame: strip whitespace and apply title case to both the name and region columns. Print the cleaned DataFrame.
customers['name'] = customers['name'].str.strip().str.title()
customers['region'] = customers['region'].str.strip().str.title()
print(customers)

  customer_id         name region
0          K1   Ravi Kumar  North
1          K2  Sita Sharma  South
2          K3   Amit Patel   West
3          K4   Neha Gupta  North
4          K5  Pooja Singh  South

In [97]:
products

  product_id product_name     category     price
0        W01     Widget A  Electronics   Rs. 500
1        W02     Widget B     Clothing   Rs. 300
2        W03     Widget C          NaN   Rs. 800
3        W04     Widget D  Electronics  Rs. 1200
4        W05     Widget E     Clothing   Rs. 450

In [98]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    5 non-null      str
 1   product_name  5 non-null      str
 2   category      4 non-null      str
 3   price         5 non-null      str
dtypes: str(4)
memory usage: 292.0 bytes

In [72]:
## (c) Clean the products DataFrame: fill the missing category with 'Home', then convert the price column from strings like 'Rs. 500' to numeric floats (by removing the 'Rs. ' prefix). Print the cleaned DataFrame.
products['category'] = products['category'].fillna('Home')
products['price'] = pd.to_numeric(products['price'].str.replace('Rs.', '').str.strip()).astype(np.float32)

In [73]:
products

  product_id product_name     category   price
0        W01     Widget A  Electronics   500.0
1        W02     Widget B     Clothing   300.0
2        W03     Widget C         Home   800.0
3        W04     Widget D  Electronics  1200.0
4        W05     Widget E     Clothing   450.0

In [74]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    5 non-null      str
 1   product_name  5 non-null      str
 2   category      5 non-null      str
 3   price         5 non-null      float32
dtypes: float32(1), str(3)
memory usage: 272.0 bytes

In [75]:
## (d) Merge all three DataFrames into a single DataFrame called report
# First merge orders (cleaned) with products (cleaned) on product_id
# Then merge the result with customers (cleaned) on customer_id
# Use left joins for both merges
# Add a new column total_value = quantity * price
# Print the shape and first 5 rows of report. (2.5 marks)

orders_with_products = pd.merge(orders, products, on='product_id', how='left')
report = pd.merge(orders_with_products, customers, on='customer_id', how='left')
report['total_value'] = report["quantity"] * report["price"]
print(report.shape)
print(report.head())

(8, 10)
  order_id customer_id product_id  quantity product_name     category   price  \
0      R01          K1        W01         2     Widget A  Electronics   500.0
1      R02          K2        W02         1     Widget B     Clothing   300.0
2      R03          K3        W03         3     Widget C         Home   800.0
3      R04          K1        W04         1     Widget D  Electronics  1200.0
4      R05          K4        W05         2     Widget E     Clothing   450.0

          name region  total_value
0   Ravi Kumar  North       1000.0
1  Sita Sharma  South        300.0
2   Amit Patel   West       2400.0
3   Ravi Kumar  North       1200.0
4   Neha Gupta  North        900.0

In [76]:
report

,order_id,customer_id,product_id,quantity,product_name,category,price,name,region,total_value
0,R01,K1,W01,2,Widget A,Electronics,500.0,Ravi Kumar,North,1000.0
1,R02,K2,W02,1,Widget B,Clothing,300.0,Sita Sharma,South,300.0
2,R03,K3,W03,3,Widget C,Home,800.0,Amit Patel,West,2400.0
3,R04,K1,W04,1,Widget D,Electronics,1200.0,Ravi Kumar,North,1200.0
4,R05,K4,W05,2,Widget E,Clothing,450.0,Neha Gupta,North,900.0
5,R06,K2,W01,4,Widget A,Electronics,500.0,Sita Sharma,South,2000.0
6,R07,K5,W02,1,Widget B,Clothing,300.0,Pooja Singh,South,300.0
7,R08,K3,W03,2,Widget C,Home,800.0,Amit Patel,West,1600.0

In [99]:
## (e) Produce a summary showing total revenue and number of orders per region, sorted by total revenue descending. Then create a pivot table with region as rows, category as columns, and total_value summed as the cell values (use fill_value=0). Print both outputs.

summary = report.groupby("region").agg(
    total_revenue = ("total_value", "sum"),
    total_orders = ("order_id", "count")
).reset_index()
print(summary)
category_region_sales = report.pivot_table(index='region', columns='category', values='total_value', aggfunc='sum', fill_value=0)
print(category_region_sales)

  region  total_revenue  total_orders
0  North         3100.0             3
1  South         2600.0             3
2   West         4000.0             2
category  Clothing  Electronics    Home
region
North        900.0       2200.0     0.0
South        600.0       2000.0     0.0
West           0.0          0.0  4000.0

In [100]:
summary

  region  total_revenue  total_orders
0  North         3100.0             3
1  South         2600.0             3
2   West         4000.0             2

In [112]:
region_wise_report = report.pivot_table(index='region', columns='category', values='total_value', aggfunc='sum', fill_value=0).reset_index()

In [113]:
region_wise_report

category region  Clothing  Electronics    Home
0         North     900.0       2200.0     0.0
1         South     600.0       2000.0     0.0
2          West       0.0          0.0  4000.0

In [105]:
report.pivot_table(index='region', columns='category', values='total_value', aggfunc=['mean', 'sum'], fill_value=0).reset_index()

         region     mean                          sum
category        Clothing Electronics    Home Clothing Electronics    Home
0         North    900.0      1100.0     0.0    900.0      2200.0     0.0
1         South    300.0      2000.0     0.0    600.0      2000.0     0.0
2          West      0.0         0.0  2000.0      0.0         0.0  4000.0

In [107]:
region_wise_report.columns

Index(['Clothing', 'Electronics', 'Home'], dtype='str', name='category')

In [108]:
region_wise_report.index

Index(['North', 'South', 'West'], dtype='str', name='region')

In [118]:
pd.melt(region_wise_report, id_vars='region', var_name='category', value_name='total_value')

  region     category  total_value
0  North     Clothing        900.0
1  South     Clothing        600.0
2   West     Clothing          0.0
3  North  Electronics       2200.0
4  South  Electronics       2000.0
5   West  Electronics          0.0
6  North         Home          0.0
7  South         Home          0.0
8   West         Home       4000.0

In [128]:
date_df = pd.DataFrame({
    "dates": ["2025-02-01", "15-01-2024", "2025-04-30"]
})
date = pd.to_datetime(date_df["dates"], format='mixed', errors='coerce', dayfirst=True)

In [129]:
date

0   2025-01-02
1   2024-01-15
2   2025-04-30
Name: dates, dtype: datetime64[us]

In [157]:
date.dt.strftime("%d-%b-%m-%Y")

0    02-Jan-01-2025
1    15-Jan-01-2024
2    30-Apr-04-2025
Name: dates, dtype: str