In [1]:
import pandas as pd

student_records = pd.DataFrame({
    'student_id': ['S001', 'S002', 'S003', 'S004', 'S005', 'S006',
                   'S007', 'S008', 'S009', 'S010', 'S011', 'S012'],
    'name':       ['Ankit Sharma', 'Neha Gupta', 'Ravi Patel', 'Ankit Sharma',
                   'Meera Joshi', 'Karan Singh', 'Pooja Rao', 'Neha Gupta',
                   'Vikram Das', 'Sonal Mehta', 'Arjun Nair', 'Divya Iyer'],
    'age':        [22, 25, -3, 22, 19, 45, None, 25, 28, 150, 21, 23],
    'city':       ['Mumbai', 'Delhi', 'Pune', 'mumbai', 'Chennai', 'DELHI',
                   'Bangalore', 'Delhi', 'Kolkata', 'Hyderabad', 'Kochi', 'pune'],
    'course':     ['Python', 'ML', 'Data Science', 'Python', None, 'Deep Learning',
                   'Python', 'ML', 'Data Science', 'ML', 'Python', 'Data Science'],
    'enrollment_date': ['2025-01-10', '2025-02-15', '2025-03-01', '2025-01-10',
                        '2025-04-20', '2027-06-15', '2025-05-05', '2025-02-15',
                        '2025-06-12', '2025-07-01', '2025-08-18', '2025-09-03']
})

Perform a data quality audit by completing the following tasks:

(a) Identify Quality Issues by Dimension (3 marks)

List at least one issue for EACH of these four dimensions. For each, specify the affected row(s)/column(s) and explain why it is a problem: Completeness, Validity, Consistency, Uniqueness.

(b) Write Pandas Code for Three Quality Checks (3 marks)

Write code for: (1) Count missing values per column, (2) Find rows with age < 0 or age > 120, (3) Detect duplicate records based on name, age, and city. State what each output reveals.

(c) Build a Mini Quality Scorecard (2 marks)

Create a summary table with columns: dimension, check_performed, issues_found, status (PASS/FAIL). Include at least four dimensions.

(d) Recommend Three Cleaning Actions (2 marks)

For each recommendation, state: (i) what action to take, (ii) which rows/columns it affects, (iii) which data quality dimension it addresses.

In [9]:
student_records.shape

(12, 6)

In [8]:
student_records

   student_id          name    age       city         course enrollment_date
0        S001  Ankit Sharma   22.0     Mumbai         Python      2025-01-10
1        S002    Neha Gupta   25.0      Delhi             ML      2025-02-15
2        S003    Ravi Patel   -3.0       Pune   Data Science      2025-03-01
3        S004  Ankit Sharma   22.0     mumbai         Python      2025-01-10
4        S005   Meera Joshi   19.0    Chennai            NaN      2025-04-20
5        S006   Karan Singh   45.0      DELHI  Deep Learning      2027-06-15
6        S007     Pooja Rao    NaN  Bangalore         Python      2025-05-05
7        S008    Neha Gupta   25.0      Delhi             ML      2025-02-15
8        S009    Vikram Das   28.0    Kolkata   Data Science      2025-06-12
9        S010   Sonal Mehta  150.0  Hyderabad             ML      2025-07-01
10       S011    Arjun Nair   21.0      Kochi         Python      2025-08-18
11       S012    Divya Iyer   23.0       pune   Data Science      2025-09-03

In [4]:
student_records.tail()

   student_id         name    age       city        course enrollment_date
7        S008   Neha Gupta   25.0      Delhi            ML      2025-02-15
8        S009   Vikram Das   28.0    Kolkata  Data Science      2025-06-12
9        S010  Sonal Mehta  150.0  Hyderabad            ML      2025-07-01
10       S011   Arjun Nair   21.0      Kochi        Python      2025-08-18
11       S012   Divya Iyer   23.0       pune  Data Science      2025-09-03

In [6]:
student_records.describe(include='all')

       student_id          name         age   city  course enrollment_date
count          12            12   11.000000     12      11              12
unique         12            10         NaN     11       4              10
top          S001  Ankit Sharma         NaN  Delhi  Python      2025-01-10
freq            1             2         NaN      2       4               2
mean          NaN           NaN   34.272727    NaN     NaN             NaN
std           NaN           NaN   39.932671    NaN     NaN             NaN
min           NaN           NaN   -3.000000    NaN     NaN             NaN
25%           NaN           NaN   21.500000    NaN     NaN             NaN
50%           NaN           NaN   23.000000    NaN     NaN             NaN
75%           NaN           NaN   26.500000    NaN     NaN             NaN
max           NaN           NaN  150.000000    NaN     NaN             NaN

In [7]:
student_records.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   student_id       12 non-null     str
 1   name             12 non-null     str
 2   age              11 non-null     float64
 3   city             12 non-null     str
 4   course           11 non-null     str
 5   enrollment_date  12 non-null     str
dtypes: float64(1), str(5)
memory usage: 708.0 bytes

In [14]:
student_records.duplicated(subset=['name', 'age', 'city', 'course', 'enrollment_date'])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
dtype: bool

Write code for:
1. Count missing values per column,
2. Find rows with age < 0 or age > 120,
3. Detect duplicate records based on name, age, and city. State what each output reveals.

In [18]:
## 1. Count missing values per column
student_records.isna().sum()

student_id         0
name               0
age                1
city               0
course             1
enrollment_date    0
dtype: int64

In [23]:
## Find rows with age < 0 or age > 120
student_records[(student_records['age'] < 0) | (student_records['age'] > 120)]

  student_id         name    age       city        course enrollment_date
2       S003   Ravi Patel   -3.0       Pune  Data Science      2025-03-01
9       S010  Sonal Mehta  150.0  Hyderabad            ML      2025-07-01

In [24]:
## Detect duplicate records based on name, age and city. State what each output reveals.
student_records.duplicated(subset=['name', 'age', 'city'])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
dtype: bool

In [25]:
student_records['city'] = student_records['city'].str.lower()

In [26]:
student_records

   student_id          name    age       city         course enrollment_date
0        S001  Ankit Sharma   22.0     mumbai         Python      2025-01-10
1        S002    Neha Gupta   25.0      delhi             ML      2025-02-15
2        S003    Ravi Patel   -3.0       pune   Data Science      2025-03-01
3        S004  Ankit Sharma   22.0     mumbai         Python      2025-01-10
4        S005   Meera Joshi   19.0    chennai            NaN      2025-04-20
5        S006   Karan Singh   45.0      delhi  Deep Learning      2027-06-15
6        S007     Pooja Rao    NaN  bangalore         Python      2025-05-05
7        S008    Neha Gupta   25.0      delhi             ML      2025-02-15
8        S009    Vikram Das   28.0    kolkata   Data Science      2025-06-12
9        S010   Sonal Mehta  150.0  hyderabad             ML      2025-07-01
10       S011    Arjun Nair   21.0      kochi         Python      2025-08-18
11       S012    Divya Iyer   23.0       pune   Data Science      2025-09-03

In [36]:
import numpy as np
student_records.loc[
  (student_records['age'] < 0) | (student_records['age'] > 120),
  'age'
] = None
mean_age = student_records['age'].mean()
student_records['age'] = student_records['age'].fillna(mean_age).astype(np.int64)
student_records

25.416666666666668
25.0

   student_id          name  age       city         course enrollment_date
0        S001  Ankit Sharma   22     mumbai         Python      2025-01-10
1        S002    Neha Gupta   25      delhi             ML      2025-02-15
2        S003    Ravi Patel   25       pune   Data Science      2025-03-01
3        S004  Ankit Sharma   22     mumbai         Python      2025-01-10
4        S005   Meera Joshi   19    chennai            NaN      2025-04-20
5        S006   Karan Singh   45      delhi  Deep Learning      2027-06-15
6        S007     Pooja Rao   25  bangalore         Python      2025-05-05
7        S008    Neha Gupta   25      delhi             ML      2025-02-15
8        S009    Vikram Das   28    kolkata   Data Science      2025-06-12
9        S010   Sonal Mehta   25  hyderabad             ML      2025-07-01
10       S011    Arjun Nair   21      kochi         Python      2025-08-18
11       S012    Divya Iyer   23       pune   Data Science      2025-09-03

In [43]:
student_records.drop_duplicates(
    subset=['name', 'age', 'city']
).reset_index()

(12, 6)

,index,student_id,name,age,city,course,enrollment_date
0,0,S001,Ankit Sharma,22,mumbai,Python,2025-01-10
1,1,S002,Neha Gupta,25,delhi,ML,2025-02-15
2,2,S003,Ravi Patel,25,pune,Data Science,2025-03-01
3,4,S005,Meera Joshi,19,chennai,NaN,2025-04-20
4,5,S006,Karan Singh,45,delhi,Deep Learning,2027-06-15
5,6,S007,Pooja Rao,25,bangalore,Python,2025-05-05
6,8,S009,Vikram Das,28,kolkata,Data Science,2025-06-12
7,9,S010,Sonal Mehta,25,hyderabad,ML,2025-07-01
8,10,S011,Arjun Nair,21,kochi,Python,2025-08-18
9,11,S012,Divya Iyer,23,pune,Data Science,2025-09-03