<a href="https://colab.research.google.com/github/Alok-Senapati/Masai-IITP-AIML-Assignments/blob/main/Assignment18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Importing required packages
import pandas as pd

In [2]:
## Reading customer data
customer_data = pd.read_csv('/content/customer_data.csv')
print(customer_data.shape)

(15, 6)

In [3]:
## Exploring the data
customer_data

,customer_id,signup_date,cancellation_date,monthly_fee,subscription_tier,total_watch_hours
0,C001,2024-01-15,2024-06-20,$9.99,Basic,245
1,C002,2024-02-10,NaN,12.99,Standard,1203
2,C003,2024-03-01,2024-03-15,$7.99,Basic,12
3,C004,2024-01-05,NaN,$15.99,Premium,3456
4,C005,2024-02-20,2024-04-10,$9.99,Basic,85
5,C006,2024-03-12,NaN,$12.99,Standard,430
6,C007,2024-01-22,2024-02-18,$7.99,Basic,5
7,C008,2024-02-05,NaN,$15.99,Premium,2200
8,C009,2024-03-18,2024-05-01,$12.99,Standard,150
9,C010,2024-01-30,NaN,$9.99,Basic,320
10,C011,2024-02-11,2024-03-02,$7.99,Basic,18
11,C012,2024-03-03,NaN,$15.99,Premium,4100
12,C013,2024-01-09,2024-02-10,$9.99,Basic,34
13,C014,2024-02-27,NaN,$12.99,Standard,760
14,C015,2024-03-10,2024-03-25,$7.99,Basic,9

In [4]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        15 non-null     object
 1   signup_date        15 non-null     object
 2   cancellation_date  8 non-null      object
 3   monthly_fee        15 non-null     object
 4   subscription_tier  15 non-null     object
 5   total_watch_hours  15 non-null     int64
dtypes: int64(1), object(5)
memory usage: 852.0+ bytes

In [5]:
customer_data.describe()

       total_watch_hours
count          15.000000
mean          868.466667
std          1327.834158
min             5.000000
25%            26.000000
50%           245.000000
75%           981.500000
max          4100.000000

In [6]:
## Part 1 - Clean the data
customer_data['monthly_fee'] = pd.to_numeric(customer_data['monthly_fee'].str.replace('$', '').str.strip(), errors='coerce')
customer_data['signup_date'] = pd.to_datetime(customer_data['signup_date'], yearfirst=True, errors='coerce')
customer_data['cancellation_date'] = pd.to_datetime(customer_data['cancellation_date'], yearfirst=True, errors='coerce')
customer_data

,customer_id,signup_date,cancellation_date,monthly_fee,subscription_tier,total_watch_hours
0,C001,2024-01-15,2024-06-20,9.99,Basic,245
1,C002,2024-02-10,NaT,12.99,Standard,1203
2,C003,2024-03-01,2024-03-15,7.99,Basic,12
3,C004,2024-01-05,NaT,15.99,Premium,3456
4,C005,2024-02-20,2024-04-10,9.99,Basic,85
5,C006,2024-03-12,NaT,12.99,Standard,430
6,C007,2024-01-22,2024-02-18,7.99,Basic,5
7,C008,2024-02-05,NaT,15.99,Premium,2200
8,C009,2024-03-18,2024-05-01,12.99,Standard,150
9,C010,2024-01-30,NaT,9.99,Basic,320
10,C011,2024-02-11,2024-03-02,7.99,Basic,18
11,C012,2024-03-03,NaT,15.99,Premium,4100
12,C013,2024-01-09,2024-02-10,9.99,Basic,34
13,C014,2024-02-27,NaT,12.99,Standard,760
14,C015,2024-03-10,2024-03-25,7.99,Basic,9

In [7]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        15 non-null     object
 1   signup_date        15 non-null     datetime64[ns]
 2   cancellation_date  8 non-null      datetime64[ns]
 3   monthly_fee        15 non-null     float64
 4   subscription_tier  15 non-null     object
 5   total_watch_hours  15 non-null     int64
dtypes: datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 852.0+ bytes

In [8]:
## Part 2 - Indicate a churn indicator
customer_data['is_churned'] = customer_data['cancellation_date'].notna().astype('int')
customer_data

,customer_id,signup_date,cancellation_date,monthly_fee,subscription_tier,total_watch_hours,is_churned
0,C001,2024-01-15,2024-06-20,9.99,Basic,245,1
1,C002,2024-02-10,NaT,12.99,Standard,1203,0
2,C003,2024-03-01,2024-03-15,7.99,Basic,12,1
3,C004,2024-01-05,NaT,15.99,Premium,3456,0
4,C005,2024-02-20,2024-04-10,9.99,Basic,85,1
5,C006,2024-03-12,NaT,12.99,Standard,430,0
6,C007,2024-01-22,2024-02-18,7.99,Basic,5,1
7,C008,2024-02-05,NaT,15.99,Premium,2200,0
8,C009,2024-03-18,2024-05-01,12.99,Standard,150,1
9,C010,2024-01-30,NaT,9.99,Basic,320,0
10,C011,2024-02-11,2024-03-02,7.99,Basic,18,1
11,C012,2024-03-03,NaT,15.99,Premium,4100,0
12,C013,2024-01-09,2024-02-10,9.99,Basic,34,1
13,C014,2024-02-27,NaT,12.99,Standard,760,0
14,C015,2024-03-10,2024-03-25,7.99,Basic,9,1

In [12]:
## Part 3 - Calculate churn rate by subscription tier
churn_rate = customer_data.groupby('subscription_tier')['is_churned'].agg(
    churned_customers='sum',
    total_customers='count'
).assign(
    churn_rate_pct = lambda x: x['churned_customers'] / x['total_customers'] * 100
).reset_index().sort_values(
    'churn_rate_pct', ascending=False
)[['subscription_tier', 'churn_rate_pct']]
churn_rate

  subscription_tier  churn_rate
0             Basic        87.5
2          Standard        25.0
1           Premium         0.0

In [14]:
## Part 4 - Identify a pattern
customer_data.groupby('is_churned')['total_watch_hours'].sum().reset_index()

   is_churned  total_watch_hours
0           0              12469
1           1                558

In [ ]:
## From the above, it is observed that the churned customers had less watch hours than active couples